#!/usr/bin/env bash
# Display domain or subdomain information
# shellcheck disable=SC2086
dinfo () {
    domain_line=$(dig $2.$1 | awk '/ANSWER SECTION:/ {getline;print}')
    r_type=$(echo $domain_line | cut -d " " -f 4)
    web_ip=$(echo $domain_line | cut -d " " -f 5)
    echo "The subdomain $2 is a $r_type record and points to $web_ip"
}
if [ $# -eq 1 ]; then
    dinfo "$1" "www"
    dinfo "$1" "1636-lb-01"
    dinfo "$1" "1636-web-01"
    dinfo "$1" "1636-web-02"
else
    dinfo "$1" "$2"
fi
