#!/usr/bin/env bash
#Install load balancer
sudo apt update
sudo apt-get install -y haproxy=1.6.\*
setup="
frontend firstbalance
	  bind *:80
	  mode http
          default_backend webservers
backend webservers
	balance roundrobin
	server 1636-web-01 34.75.156.173 check
	server 1636-web-02 35.243.219.163 check
"
echo "$setup" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
