#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
count=1
while [[ $count -le 9 ]];
  do
    if [[ $count -eq 9 ]]; then
      echo "Hi"
    fi
    echo "Holberton School"
    count=$((count+1))
  done
