#!/usr/bin/env bash
#Prints Holberton School to stdout 10 times with a while loop.
count=1
word="Holberton School"
while [ $count -lt 11 ];
do
    if [ $count -eq 4 ];
    then
	echo "bad lock"
    elif [ $count -eq 8 ];
    then
	echo "good lock"
    else
	echo "$word "
    fi
    count=$(( count + 1 ))
done
