#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
count=1
word="Holberton School"
while [ $count -lt 10 ];
do
    if [ $count -eq 4 ];
    then
	echo "bad lock"
    elif [ $count -eq 8 ];
    then
	echo "good lock"
    else
	echo "$word "
    fi
    count=$(( count + 1 ))
done
